//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Pl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Market_Main = new HashSet<Market_Main>();
        }
    
        public int Departments_id { get; set; }
        public string Departments_Nomination { get; set; }
        public string Departments_Surname { get; set; }
        public string Departments_Name { get; set; }
        public string Departments_Patronymic { get; set; }
        public string Departments_Number { get; set; }
        public string Departments_Implementation { get; set; }

        public string Nomination
        {
            get
            {
                return "Код отдела: " + this.Departments_Nomination;
            }
        }
        public string Surname
        {
            get
            {
                return "Фамилия руководителя: " + this.Departments_Surname;
            }
        }
        public string Name
        {
            get
            {
                return "Имя руководителя: " + this.Departments_Name;
            }
        }
        public string Patronymic
        {
            get
            {
                return "Отчество руководителя: " + this.Departments_Patronymic;
            }
        }
        public string Number
        {
            get
            {
                return "Номер: " + this.Departments_Number;
            }
        }
        public string Implementation
        {
            get
            {
                return "Объем: " + this.Departments_Implementation;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Market_Main> Market_Main { get; set; }
    }
}
