//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Pl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market_User
    {
        public int Market_User_id { get; set; }
        public string Market_User_Login { get; set; }
        public string Market_User_Password { get; set; }
    }
}
