//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Pl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sell()
        {
            this.Market_Main = new HashSet<Market_Main>();
        }
    
        public int Sell_id { get; set; }
        public string Sell_Article { get; set; }
        public string Sell_Date { get; set; }
        public string Sell_Unit { get; set; }

        public string Article
        {
            get
            {
                return "Артикул: " + this.Sell_Article;
            }
        }
        public string Date
        {
            get
            {
                return "Дата продажи: " + this.Sell_Date;
            }
        }
        public string Unit
        {
            get
            {
                return "Кол-во проданного товара: " + this.Sell_Unit;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Market_Main> Market_Main { get; set; }
    }
}
